### ISSUE TITLE
Shows same index for each element on diff upon removal of multiple items from array

### ISSUE THREAD

**Issue by RyanSept** [stefankoegl/python-json-patch#105]
**Version: 1.24**

**Description**
When multiple elements are removed from a list, the index on the path for each removed element is the same.

**Steps to reproduce**
```
d1 = {'fruits': ['banana', 'mango', 'apple', 'tomato']}
d2 = {'fruits': ['banana']}
d3 = {'fruits': []}

jsonpatch.make_patch(d1, d2).patch

# [{u'op': u'remove', u'path': u'/fruits/1'},
# {u'op': u'remove', u'path': u'/fruits/1'},
# {u'op': u'remove', u'path': u'/fruits/1'}]

## Expected
# [{u'op': u'remove', u'path': u'/fruits/1'},
# {u'op': u'remove', u'path': u'/fruits/2'},
# {u'op': u'remove', u'path': u'/fruits/3'}]

jsonpatch.make_patch(d1, 3).patch

# [{u'op': u'remove', u'path': u'/fruits/0'},
# {u'op': u'remove', u'path': u'/fruits/0'},
# {u'op': u'remove', u'path': u'/fruits/0'},
# {u'op': u'remove', u'path': u'/fruits/0'}]

## Expected
# [{u'op': u'remove', u'path': u'/fruits/0'},
# {u'op': u'remove', u'path': u'/fruits/1'},
# {u'op': u'remove', u'path': u'/fruits/2'},
# {u'op': u'remove', u'path': u'/fruits/3'}]

```

Though the resulting patch can be applied to ultimately obtain the same result, the patch is a bit idiosyncratic. Is this intentional and if so why?

I'm happy to take on this issue if you agree on this

**Comment by itkach** [comment]
Patch is a list of operations to be applied to original data structure to produce resulting data structure, so what `jsonpatch.make_patch` currently produces makes sense and is expected - corresponds to removing elements one by one from the head of the list. This is not the only way to achieve the same result, e.g. implementation could be removing elements the tail and generate 
```
[{u'op': u'remove', u'path': u'/fruits/3'},
{u'op': u'remove', u'path': u'/fruits/2'},
{u'op': u'remove', u'path': u'/fruits/1'}]
```
which is perhaps somewhat more humanly readable, but current implementation is just as valid.

**Comment by RyanSept** [comment]
Hi @itkach  👋 . I totally agree. I felt if we can have the human readability it'd be a plus for our use-case which shows the diff to users on a UI.

**Comment by stefankoegl** [comment]
Both the currently produced patch and the one mentioned by @itkach should be valid according to the spec.

@RyanSept, if you want to provide a pull request to produce the other version, I am happy to review it.
