### ISSUE TITLE
Custom types no longer work

### ISSUE THREAD

**Issue by clj** [stefankoegl/python-json-patch#107]
The change introduced by #103 jsonpatch uses `json.dumps` to check for equality. This breaks when using Python structures that were deserialized using custom types. In our case this happens because floats are deserialized as `decimal.Decimal`. When calling: `JsonPatch.from_diff(old, new)` this now causes a `TypeError: Decimal('1') is not JSON serializable`.

### Possible fixes:
1. Explicitly only support the types natively supported by the built in json module
2. Use the simplejson module instead of the builtin json module (at the expense of an extra dependency) to at least support the `decimal.Decimal` type
3. Allow a custom `dumps` implementation to be passed to `from_diff` (and possibly when creating instances of `JsonPatch` to make `JsonPatch.to_string` also work with custom types, although this is easy to work around using the `JsonPatch.patch` attribute).

Option 3 exposes what could be considered an implementation detail (the use of `dumps` for comparisons). However if custom types are to be supported at all, I wonder if this is not the only way that things will work. For example, I can casually construct an example (using custom types) where two values compare equal before serialization but not after:

```python
>>> decimal.Decimal('1.0') == decimal.Decimal('1.00')
True

>>> simplejson.dumps(decimal.Decimal('1.0')) == simplejson.dumps(decimal.Decimal('1.00'))
False
```

The only way to know, in a generic way, whether the two things that use custom types should generate a patch op or not would be to serialize them, as far as I can tell.

**Comment by stefankoegl** [comment]
Fixed by #108
