### ISSUE TITLE
Feature Request - patch creation should fail when given an invalid patch

### ISSUE THREAD

**Issue by dave-shawley** [stefankoegl/python-json-patch#110]
I use this library to implement `PATCH` in a number of JSON-based APIs and it works quite well.  I do have one nagging issue though.  I do not have a good way to verify that the document I am given is a valid `application/json-patch+json` instance until I try to apply the patch to another document.  Usually this means that I have retrieved a representation to update from somewhere (e.g, database), then I apply the patch.  If the patch is not a valid document, then I bothered my database unnecessarily.

Would you accept a PR to add a new method, `jsonpatch.JsonPatch.validate`, that performs the sanity checking done in the [_ops property](https://github.com/stefankoegl/python-json-patch/blob/9e4d423c22bedad6ffc260541ae587114dfed70a/jsonpatch.py#L291-L293) today?

**Comment by Alanscut** [comment]
Hi @dave-shawley, PR is always welcome :)
