### ISSUE TITLE
Support for MutableMappings / MutableSequences

### ISSUE THREAD

**Issue by andrewmichaelsmith** [stefankoegl/python-json-patch#33]
Hi

This may or may not qualify as a bug in your eyes but thought I'd report it. 

Basically I have a project where I have implemented MutableMapping and MutableSequenece (https://docs.python.org/3/library/collections.abc.html`). 

If I try and apply a patch (patch.apply) to my MutableMapping I get this error:

```
/usr/local/lib/python2.7/dist-packages/jsonpatch.py", line 344, in apply
    obj = operation.apply(obj)
  File "/usr/local/lib/python2.7/dist-packages/jsonpatch.py", line 412, in apply
    "invalid document type %s" (type(doc),)
NameError: global name 'doc' is not defined
```

I assume this is because you're using `isinstance(subobj, dict)` to check if something is a dict (i.e. https://github.com/stefankoegl/python-json-patch/blob/master/jsonpatch.py#L422) and deciding my object is neither a list or a dict. 

I suppose one way to fix this would be to have `isinstance(subobj, dict) or isinstance(subjobj, MutableMapping)`.

(looking at code on github I suspect this error would be slightly different, I'm currently on `jsonpatch.__version__ == 1.3`)

Any thoughts?

**Comment by mattupstate** [comment]
Unfortunately not every `list`-like or `dict`-like data structure across various Python libraries inherit from `MutableSequence` or `MutableMapping` but rather implement the various {non-}magic methods to behave as a `list` or `dict`. In my case, I'm trying to append an object to a `list`-like datastructure (specifically [this](https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/ext/associationproxy.py#L517)).

I understand that these ABC's are probably the most reliable way to do some type checking but I wonder if there's a way to support other objects that implement the expected methods for these operations.

**Comment by stefankoegl** [comment]
I am not sure how you'd otherwise distinguish between lists and dicts. Previous version checked if the class were subclasses of either, but those cases are covered by the ABC as well. Maybe I'm just missing something obvious... any suggestions?

**Comment by mattupstate** [comment]
I don't think you're missing anything obvious. I'm in a state of "I wonder why this doesn't work with <insert data structure here>" and decided to write something here in case something wasn't obvious to me :smirk:

**Comment by stefankoegl** [comment]
The best solution would probably to fix [zzzeek/sqlalchemy](https://github.com/zzzeek/sqlalchemy/) so that the correct ABC are used ;)
