### ISSUE TITLE
Key order

### ISSUE THREAD

**Issue by st0nx** [stefankoegl/python-json-patch#35]
if I have the key order:
"{"path": "/cvc", "value": 1112, "op": "replace"}"
I get an InvalidJsonPatch: Operation does not contain 'op' member.
It arises because " _get_operation" take the keys in the order where the first "op".

**Comment by stefankoegl** [comment]
I don't see where ``_get_operation`` would rely on the key order. Can you please provide a full example that raises a ``InvalidJsonPatch`` in the case you describe?

**Comment by stefankoegl** [comment]
No response - closing. Feel free to comment, and I will reopen.
