### ISSUE TITLE
json.load method overriding

### ISSUE THREAD

**Issue by BlueMonday** [stefankoegl/python-json-patch#37]
Hello!

I was wondering why `json.load` is overridden and set to a partial. It doesn't seem like `json.load` is used at all in the library, instead `json.loads` is used. The way it is currently set up, importing `jsonpatch` will result in a different behaviour for `json.load`. 

This is due to these specific lines in `jsonpatch`: 

```python
import json 
json.load = ... 
```

This led to a bunch of really sneaky bugs... I was trying to use the `object_hook` of `json.load` but some library I was using imported `jsonpatch` which sets the `object_pairs_hook` parameter so `object_hook` was not being used (if `object_pairs_hook` is not None it gets used instead of `object_hook`). 

If the intention was to override `json.loads` can it be done in a way that doesn't affect every library that imports `jsonpatch`? If that is not the case could the override be removed since it is not used?

I am not known for being good at explaining... Let me know if you want me to clarify!

@stefankoegl

**Comment by stefankoegl** [comment]
This was introduced in 4d0389238e1d963f859af42a9a0fa38483a7fa41, apparently to handle cases where the keys in a JSON object are not unique. In retrospect it seems like monkey-patching ``json.loads`` was not necessary, I could have created an internal alias instead. 

I'll fix this for the next version.

**Comment by jakul** [comment]
@stefankoegl I just had this bug bite me

**Comment by stefankoegl** [comment]
I have implemented a fix in branch `jsonload-no-override` (#72), which will go into the next release.
