### ISSUE TITLE
Feature request: patch using jsonpointer

### ISSUE THREAD

**Issue by austinnichols101** [stefankoegl/python-json-patch#60]
@stefankoegl - thanks for all of your work. 

Feature request - 

I am manually constructing a patch from a set of pre-created jsonpointer objects.  When I create the patch I'm using the `path` property of the pointer:

`patch.append({'op': 'add', 'path': pointer.path, 'value': value })`

For large documents, this creates a small bit of overhead as I'm having pointer convert to a path, and then back again when `jsonpointer.JsonPointer.from_parts` is called when the patch is applied.  

I would like to be able to use just `pointer` instead of `pointer.path` .  No sense in parsing twice...

**Comment by stefankoegl** [comment]
Hi,

Thanks for your suggestion. I agree that this would make sense.

I do, however, not have enough time lately to devote to projects like ``jsonpatch``. If you'd be interested in providing a pull request, I'd try to review it quickly and prepare a release. 

As far as I can tell, it would be sufficient to add a type check to ``PatchOperation.__init__()``, and add corresponding tests.

**Comment by stefankoegl** [comment]
I have created pull request #75 which implements the feature you describe. You can have a look at branch `jsonptr` to see if this works for you.

**Comment by stefankoegl** [comment]
Closed by #75

**Comment by stefankoegl** [comment]
I've just released v1.23 which contains this functionality.
