### ISSUE TITLE
Version in jsonpatch.py is 1.15 not 1.16

### ISSUE THREAD

**Issue by petedmarsh** [stefankoegl/python-json-patch#64]
I just noticed that  `__version__` in `jsonpatch.py` is `1.15` but the current release version is 1.16 - the commit bumping to 1.16 appears to be missing from master (https://github.com/stefankoegl/python-json-patch/commit/1fc5e2022ff2c5796bd28af56646b135ede4ee71).

**Comment by stefankoegl** [comment]
The commit is here (1fc5e2022ff2c5796bd28af56646b135ede4ee71), but not part of `master`. I'm not yet sure what happened here...

**Comment by stefankoegl** [comment]
I've created a merge commit to reconcile both. Thanks a lot for pointing that out :)
