### ISSUE TITLE
Please package the next version as v1.20

### ISSUE THREAD

**Issue by geofft** [stefankoegl/python-json-patch#67]
Hi, I'm working on updating the packaging for python-json-patch in Debian, and it looks like at some point in the past, we had packaged v1.10 as v1.19 (I'm not sure if this was a previous Debian maintainer making a typo, or a v1.19 tag in the upstream repo - we have [a git commit that claims to merge the v1.19 tag](https://anonscm.debian.org/cgit/openstack/python/python-json-patch.git/commit/?h=debian/liberty&id=586cda77ff999a096347e61c2f1807dc61221d2b), but no such tag currently exists in your repo). This mistake has also propagated to downstream distributions including Ubuntu.

Since we need version numbers to increase for upgrades to happen, Ubuntu is working around this by calling the latest version "1.19+really1.16", which sorts after "1.19" (see https://pad.lv/1704024), and I'll do the same in Debian.

Do you mind giving the next release the version number 1.20, so that we can resynchronize and get onto reasonable version numbers? Sorry about the trouble, and thanks for your software!

**Comment by stefankoegl** [comment]
I have just released a new version as 1.20.

Thanks for the work you do on Debian packaging - this is very much appreciated!
