### ISSUE TITLE
escape sequences not implemented

### ISSUE THREAD

**Issue by nielslaukens** [stefankoegl/python-json-patch#73]
[RFC6901 section 3](https://tools.ietf.org/html/rfc6901#section-3) defines the syntax for the `path` part of an operation. It specifies 2 escape sequences for keys that must be used. Currently, python-json-patch does not implement these correctly.

Test case:
```python
import jsonpatch
jsonpatch.apply_patch({}, {'op': 'add', 'path': '/test-0123-1456', 'value': 42})
```

expected result:
`{'test-123/456': 42}`

actual result:
`{'test-0123-1456': 42}`

**Comment by stefankoegl** [comment]
The escape sequence that you are referring to is `~1`, which is handled correctly.

````python
>>> import jsonpatch
>>> doc = {'a/b': 1}
>>> p = jsonpatch.make_patch({}, doc)
>>> str(p)
'[{"op": "add", "path": "/a~1b", "value": 1}]'
>>> p.apply({})
{'a/b': 1}
````

**Comment by nielslaukens** [comment]
My apologies... I should really switch to a larger font...
