### ISSUE TITLE
unit test test_js_file fails when running it from pypi

### ISSUE THREAD

**Issue by amoralej** [stefankoegl/python-json-patch#82]
When try to run unit tests with the tarbal from https://pypi.io/packages/source/j/jsonpatch/jsonpatch-1.21.tar.gz:

ERROR: test_js_file (__main__.ApplyPatchTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests.py", line 17, in test_js_file
    with open('./tests.js', 'r') as f:
IOError: [Errno 2] No such file or directory: u'./tests.js'

Root cause is missing tests.js file from tarbal, could it be added to the package?

**Comment by yurivict** [comment]
I'm getting this too.

**Comment by stefankoegl** [comment]
Thanks for letting me know. This fix will be included in the next release.
