### ISSUE TITLE
Replace operations details

### ISSUE THREAD

**Issue by smehta** [stefankoegl/python-json-patch#85]
I am using  patch = jsonpatch.make_patch(src, dst) operation.

I am wondering when the op = 'replace', Is it possible to know what exactly has changed between 2 json object ?  I was curious to know if it can do deep comparison.

**Comment by stefankoegl** [comment]
I'm not sure if I understand correctly. Can you give an example?

**Comment by smehta** [comment]
Sure. Let say I have an original json and updated one. Only difference between them is owner property has changed from user1 to user2.  

Original :```
 {  'owner': 'user1',   'title': 'Cover Letter'  },   
                'identifier': { 'schemaUuid': "82c09b19-3630-429e-bf77-470ff4bf74f1",
                                    "version": 1  },   
               "name": "Cover Letter"}
```
Updated: 
```
{  'owner': 'user2',   'title': 'Cover Letter'  },   
                'identifier': { 'schemaUuid': "82c09b19-3630-429e-bf77-470ff4bf74f1",
                                    "version": 1  },   
               "name": "Cover Letter"}
```

Currently, out of make_patch operation will say that I need to replace the entire object. Is it possible to know what exactly has changed ? i.e owner attribute has changed. I understand this is not exactly part of JSON patch specification but I was wondering if library has support for this.

**Comment by stefankoegl** [comment]
Can you please give a full example. When I do the following, I get the result that you intend to have.

```` python
>>> src = { 'owner': 'user1', 'title': 'Cover Letter', 'identifier': { 'schemaUuid': "82c09b19-3630-429e-bf77-470ff4bf74f1", "version": 1 }, "name": "Cover Letter"}
>>> dst = { 'owner': 'user2', 'title': 'Cover Letter', 'identifier': { 'schemaUuid': "82c09b19-3630-429e-bf77-470ff4bf74f1", "version": 1 }, "name": "Cover Letter"}
>>> 
>>> import jsonpatch
>>> list(jsonpatch.make_patch(src, dst))
[{'path': '/owner', 'op': 'replace', 'value': 'user2'}]
````

**Comment by smehta** [comment]
Thanks stefan for following up. I wasn't creating my data structure correctly. I just paid little more attention the way I do that and its working as expected. 

Thank you for your help. much appreciated.
